site_name: Web Development Using PHP, CakePHP

theme: readthedocs

pages:
- [index.md, Home]
- [motivation.md, Motivation]
- [unit-3/php-1.md, PHP 1.0]
- [unit-3/php-installation.md, Installing PHP]
- [unit-3/how-web-works.md, How Web Works]
- [unit-3/how-php-works.md, How PHP Works]
- [unit-3/data-types.md, Data Types]
- [unit-3/constants.md, Constants]
- [unit-3/arrays.md, Arrays in PHP]
- [unit-3/u3-handson.md, Lets Do something]
- [unit-3/u3-echo.md, Displaying content in PHP]
- [unit-4/functions.md, Functions]
- [unit-4/scope.md, Variable Scope]
- [unit-5/class.md, Object Oriented Programming]
- [unit-5/constructors.md, Constructors & Destructors]
- [unit-5/visibility.md, Visibility]
- [unit-5/self-this.md, Self & this Special Varialbles]
- [unit-5/inheritance.md, Inheritance]
- [useful-html-entities.md, Useful HTML Entities]
- [useful-ini-settings.md, Useful ini Settings]
- [further-readings.md, Further Readings on PHP]
- [refe.md, References]